docs(partition): add an overload for better typing
ReactiveX/rxjs pull request #5756
Opened 2020-09-25 02:10 UTC by tech6hutch

**Description:**

Just adds a new overload to `partition` to give more useful types, similar to the one for `filter`. I found myself wanting this feature, and It seemed easy enough to implement.

2020-09-29 02:41 UTC, benlesh requested changes
Thank you so much for this contribution! Looks like we need some dtslint tests to prove that the typings are indeed better.

(I'm not sure if we actually have any for this one yet, TBH)

2020-10-01 02:29 UTC, tech6hutch commented
> Thank you so much for this contribution! Looks like we need some dtslint tests to prove that the typings are indeed better.
> 
> (I'm not sure if we actually have any for this one yet, TBH)

I uh, don't know how to do that, tbh. 😅

2020-10-02 20:07 UTC, benlesh commented
@tech6hutch Well, if you're willing to give it a go, all you'd have to do is look at some of the files under `spec-dtslint` and try adding one for `partition`. To run those tests, you just run `npm run dtslint`. 

If you're not, just let me know, and I'll try to find time to do it.

2021-03-18 12:21 UTC, cartant approved these changes
@benlesh I've added some dtslint tests and I've updated the PR author's changes to include the `thisArg` changes.

2021-03-18 13:43 UTC, benlesh approved these changes

2021-03-18 13:44 UTC, merged

2021-03-18 13:53 UTC, tech6hutch commented
I forgot about this - thanks for finishing it!