docs(skip): add description and example for the operator
ReactiveX/rxjs pull request #5773
Opened 2020-09-29 17:41 UTC by hardikpthv

**Description:**
- Add description, example, and See Also section for the `skip` operator

**Related issue (if exists):**
- Closes #4868

2020-09-29 21:00 UTC, niklas-wortmann requested changes
Hi one minor thing again :D Many thanks for you contributions I really appreciate it

2020-09-29 21:00 UTC, niklas-wortmann commented on src/internal/operators/skip.ts
> + * is over when source is reached to its limit.
Can you delete this last sentence. I get what you are saying, but I think this causes more confusion than it helps the reader

2020-09-30 07:41 UTC, hardikpthv commented
> Hi one minor thing again :D Many thanks for you contributions I really appreciate it

You're welcome, @niklas-wortmann! Happy to contribute :)

2020-09-30 14:41 UTC, niklas-wortmann approved these changes
LGTM

2020-09-30 14:41 UTC, merged