refactor(combineLatest): Improve types
ReactiveX/rxjs pull request #5847
Opened 2020-10-22 22:04 UTC by benlesh

- Reduces some type complexity in combineLatest
- Improves types around resultSelectors

2020-10-22 23:28 UTC, cartant requested changes

2020-10-22 23:28 UTC, cartant commented on spec-dtslint/observables/combineLatest-spec.ts
> +  const o = combineLatest(a$, (a) => new A()); // $ExpectType Observable<A>
nitpick: Specifying the parameter here does nothing, ATM, but we could improve the tests by using them:

```ts
const o = combineLatest(a$, (a) => [a] as const); // $ExpectType Observable<[A]>
```

2020-10-22 23:28 UTC, cartant commented on src/internal/observable/combineLatest.ts
> +  sources: readonly [...ObservableInputTuple<A>],
issue: `R` is not used in this sig. The return type should be `Observable<A>`, AFAICT.

nitpick: Why is the surrounding `[... ]` needed? Why not `sources: ObservableInputTuple<A>`? This occurs elsewhere, too.

2020-10-22 23:28 UTC, cartant commented on src/internal/observable/combineLatest.ts
> +export function combineLatest<A extends readonly unknown[]>(...sources: [...ObservableInputTuple<A>, SchedulerLike]): Observable<A>;
question: Why does this use an approach that differs from what's done with `merge`? Does this behave a little better? Are there tests to show this?

2020-10-26 21:46 UTC, cartant commented on src/internal/observable/combineLatest.ts
> +  sources: readonly [...ObservableInputTuple<A>],
Having used this, I can see, now, that the `[... ]` business is needed.

2020-10-27 00:52 UTC, kolodny approved these changes
I'm loving these PRs. I just feel for the Google folks who need to sync this in. Anyone with explicit generics is gonna have a bad time.

🔥🔥🔥🔥🔥🔥🔥🔥🔥 
![image](https://user-images.githubusercontent.com/1187604/97243490-d3da5300-17cc-11eb-8156-2ca6276b815e.png)

2020-10-27 00:52 UTC, kolodny commented on src/internal/observable/combineLatest.ts
> +  sources: readonly [...ObservableInputTuple<A>],
OOO is `readonly` needed here? Doesn't make a difference IMO, purely curious

2021-03-13 07:38 UTC, cartant commented
Closing this 'cause the `combineLatest` types have been refactored in:

- https://github.com/ReactiveX/rxjs/pull/6092
- https://github.com/ReactiveX/rxjs/pull/6103

2021-03-13 07:38 UTC, closed without merging