refactor(zip): support N-args with result selector
ReactiveX/rxjs pull request #5884
Opened 2020-11-08 06:41 UTC by cartant

**Description:**

Updates the static `zip` to use `ObservableInputTuple`, etc.

**Related issue (if exists):** None

2020-11-17 20:16 UTC, kolodny approved these changes

2020-11-17 20:16 UTC, kolodny commented on spec-dtslint/observables/zip-spec.ts
> +  const o1 = zip(a, b, c); // $ExpectType Observable<[number, string, boolean]>
nit: can you add a test for multiple const values?

```ts
const a = from([1, 2] as const);
const b = from(['foo', 'bar'] as const);
const c = from([true, false] as const);
const o1 = zip(a, b, c); // $ExpectType Observable<[1, 'foo', true] | [2, 'bar', false]>
```

Does that work?

2020-11-17 20:51 UTC, benlesh requested changes
This seems to be missing dtslint tests for result selector

2020-12-06 01:33 UTC, benlesh approved these changes

2020-12-06 01:33 UTC, benlesh commented
Merging and moving on.

2020-12-06 01:33 UTC, merged

2020-12-06 03:51 UTC, cartant commented
@benlesh

> Merging and moving on.

I'll come back to the missing dtslint tests later in the upcoming week. Or I'll add them to the list of things for Jan-Niklas to do whist he's in quarantine. 🙂