docs: add a best practices document
ReactiveX/rxjs pull request #6157
Opened 2021-03-19 15:17 UTC by Armenvardanyan95

This is an initial version of a document describing best practices and antipatterns to avoid when using RxJS. This is a more finalized version of my draft, I tried to bring together important points mentioned by everyone in the related issue thread (#5185). Will be glad to hear how this can be improved

2021-03-19 15:19 UTC, Armenvardanyan95 commented
Important questions to be addressed:

- Do we need any more sections?
- Is the reason why subclassing is bad explained enough?
- Are the code examples okay?
- I did not update the navigation.json file, as I did not really know where should this go, if anyone directs me, I will also update that

WIll happily listen to everyone's thoughts

2021-05-05 09:04 UTC, niklas-wortmann requested changes
Hi sorry I wasn't able to review this earlier. First of all thanks for taking the time for this contribution, I do think that this is a gap in the docs we have to fill. From my point of view your suggestions have a couple personal opinions, that I don't necessarily share and I am not sure how we should incorporate those properly in the docs. Maybe other core team members have an opinion as well, @cartant, @benlesh, @kwonoj, @kolodny

2021-05-05 09:04 UTC, niklas-wortmann commented on docs_app/content/guide/best-practices.md
> +When `takeUntil` is not used correctly, it can lead to memory leaks too. As a rule of thumb, always place `takeUntil` as the last operator in the `pipe`.
can you elaborate on this a little bit to make it easier to understand for newcomers

2021-05-05 09:04 UTC, niklas-wortmann commented on docs_app/content/guide/best-practices.md
> +Sometimes, it can be tempting to build our own version of an `Observable` using existing classes. In particular, some developers might extend the existing `Observable` class to add some functionality
there's a typo in `bae`

2021-05-05 09:12 UTC, cartant commented
> Maybe other core team members have an opinion as well

I don't think this could be merged without discussion. I don't agree with everything in this PR and, FWIW, I'm reluctant to declare a list of official best practices.

2022-10-05 23:49 UTC, CMCDragonkai commented
Regarding the don't subclass section. Can you provide an alternative to this kind of usecase?

Suppose you had a domain class like `KeyRing`. The `KeyRing` is a class with properties and methods. You want the properties to be observable, and that's easy enough with third party observable decorators, but what if want the whole `KeyRing` object to be observable too?

Would that mean some sort of `BehaviourSubject` for the `KeyRing` object, so that downstream consumers can subscribe to the entire `KeyRing` and should get the pointer to the `KeyRing` object, and access all the changed properties atm.

One issue I'm thinking is that the `KeyRing` is a singleton object, it's not like new `KeyRing` is created on each change. That could meant it doesn't make sense for it to be a reactive class itself, but I'm not sure. There's not much information on whether it makes sense to subclass Observable with your own custom class, in which you want the whole domain object itself to be observable.

2026-07-22 19:23 UTC, benlesh commented
Hi @Armenvardanyan95 — thank you for the time, care, and thoughtfulness you put into this pull request. I’m sorry we weren’t able to respond in a reasonable timeframe. Since the codebase and surrounding context have moved on and this hasn’t seen recent activity, I’m going to close it for now. That’s a reflection of our delayed triage, not a lack of appreciation for your contribution. If the change is still relevant, please feel welcome to open a fresh pull request against the current codebase. Thank you again for contributing to RxJS and for your patience.

— Ben

<!-- rxjs-maintenance:close:pr:6157 -->

2026-07-22 19:23 UTC, closed without merging