docs(partition): add exclusion when using type guard
ReactiveX/rxjs pull request #6168
Opened 2021-03-22 19:27 UTC by Boudewijn26

**Description:**
Add exclusion to partition when using a type guard.

[Previously support for a user defined type guard was added to partition](https://github.com/ReactiveX/rxjs/pull/5756). This meant that Typescript could understand the first item in the resulting tuple to match a certain type. What was missing was Typescript understanding the second item in the tuple to _not_ be of that type. As an example:
```typescript
type AMessage = { a: number };
type BMessage = { b: number };
type Message = AMessage | BMessage;
const aMessage: AMessage = { a: 1 };
const bMessage: BMessage = { b: 2 };
const message$: Observable<Message> = from([aMessage, bMessage]);

function isAMessage(msg: Message): is AMessage { 
  return msg.a;
}
const [aMessage$, bMessage$] = partition(message$, isAMessage);
bMessage$.subscribe((msg) => console.log(msg.b)); // no longer fails with this change
```

Without this change Typescript would consider `bMessage$` to be the same type as `message$`: `Observable<AMessage | BMessage>`. Whereas we are sure `bMessage$` only emits `BMessage`, because all `AMessage` will be put in `aMessage$`.

2021-03-23 08:01 UTC, cartant requested changes

2021-03-23 08:01 UTC, cartant commented on src/internal/observable/partition.ts
> +): [Observable<U>, Observable<S>];
AFAICT, `S` doesn't have to be a type parameter. Instead, `Observable<Exclude<T, U>>` could be used in the return type.

2021-03-23 08:09 UTC, cartant approved these changes
LGTM. Thanks.

2021-03-23 08:17 UTC, Boudewijn26 commented
Thank you for the quick response, happy to help!

2021-03-25 14:31 UTC, benlesh approved these changes

2021-03-25 14:39 UTC, merged