Add exports within package.json to enable scoped package loading.
ReactiveX/rxjs pull request #6192
Opened 2021-03-29 21:03 UTC by samccone

In order for module resolution to work with .mjs or package: module code
we need to utilize the conditional export feature of node.

> The current specifier resolution does not support all default behavior of the CommonJS loader. One of the behavior differences is automatic resolution of file extensions and the ability to import directories that have an index file.

https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm
https://nodejs.org/api/packages.html#packages_conditional_exports

This directly enables rxjs to work with mjs code and commonjs code since
mjs does not support loading bare folder paths.

This is a fix to:
https://github.com/sveltejs/kit/issues/612

and is directly related to the conversation in this issue within node
core https://github.com/nodejs/node/issues/27408

**Description:**

**Related issue (if exists):**

2021-03-29 21:10 UTC, MylesBorins commented on package.json
> +  },
FYI this is a breaking change as it locks down the public interface of accessible deep imports. At the very least you probably want an explicit entry for the `package.json`

```suggestion
    },
    "./package.json": "./package.json"
  },
```

2021-03-29 21:16 UTC, benlesh requested changes
I'm not totally sure of the implications here. But I can see that we're missing a few spots.

2021-03-29 21:16 UTC, benlesh commented on package.json
> +    }
There would also need to be entries for:

- rxjs/testing
- rxjs/webSocket
- rxjs/fetch
- rxjs/ajax

2021-03-29 21:20 UTC, benlesh commented
I'm really glad you're looking into this, @samccone.

Also, I guess we'd need to be running some sort of simple test that shows the problem that this is fixing, and that it's working now.

Thank you, @MylesBorins for helping to review this, BTW.

2021-03-29 21:31 UTC, samccone commented
As for a test @benlesh, the test is actually quite simple!


#### test_file.mjs
```
import {Observable} from 'rxjs';
import * as o from 'rxjs/operators';
import * as a from 'rxjs/ajax';
import * as f from 'rxjs/fetch';
import * as t from 'rxjs/testing';
import * as w from 'rxjs/webSocket';

console.log(Observable, o, a, f, t, w);
```

In node 14,15 run `node test_file.mjs` against the built package. Do you have any similar tests to this currently?

2021-03-29 22:48 UTC, benlesh commented
> Do you have any similar tests to this currently?

We have some import tests that @kwonoj set up, but I'm not sure they cover this. That test is so simple that it seems like just running that would be fine, IMO.

2021-03-30 05:15 UTC, samccone commented
ok @benlesh test case added and new github workflow config has been modified to run the test.

2021-03-30 08:15 UTC, cartant approved these changes
LGTM.

Widespread support for `exports` in `package.json` is something I've been looking forward to for a long time, so this is particularly encouraging.

One thing we might want to look at - not necessarily in this PR, but it's something I think we should discuss before v7 is released - is whether we really want to be downleveling our ES modules to ES5. It's 2021 and distributing ES5 makes me cry. 😢

2021-03-30 13:51 UTC, MylesBorins commented
@cartant moving to native ESM will be an even bigger lift as Node.js doesn't support File Extension Resolution or Folder Resolution by default... So every internal import will need to be updated in the source (or modified in transpiled output). There are creative ways to continue to use extensionless imports internally without requiring any flags (Specifically [Subpath Pattern](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_subpath_patterns)), but they do require using a non-relative import specifier and I don't believe that TS supports this yet.

2021-03-30 16:08 UTC, benlesh commented
> is whether we really want to be downleveling our ES modules to ES5. It's 2021 and distributing ES5 makes me cry. 😢

Same... I want to get rid of those. Let's add it the the agenda.

> @cartant moving to native ESM will be an even bigger lift as Node.js doesn't support File Extension Resolution or Folder Resolution by default... So every internal import will need to be updated in the source (or modified in transpiled output). There are creative ways to continue to use extensionless imports internally without requiring any flags (Specifically Subpath Pattern), but they do require using a non-relative import specifier and I don't believe that TS supports this yet.

@MylesBorins Can you summarize what we need to do to be the best stewards of the community here? What should we ideally be outputting? How can we test it?

2021-03-30 16:08 UTC, benlesh approved these changes

2021-03-30 16:10 UTC, benlesh commented
Actually, @MylesBorins, if you have the time, I'd love it if you started a new issue for this with some checkboxes of what we need to have, and how we could test it? No worries if you don't have the time. We're all volunteers here. 

I want to merge this, and try to get the conversation somewhere it makes sense. <3

2021-03-30 16:10 UTC, merged