feat: change teardown to finalizer/finalization
ReactiveX/rxjs pull request #6601
Opened 2021-09-17 13:17 UTC by sangxxh

**Description:**

- Update glossary
- Update docs
- Update variable/param/type names and deprecate old type names (with jsdoc `@deprecated`) for backward compatibility

**Related issue (if exists):** Closes #6528

2021-09-19 00:17 UTC, benlesh commented on src/internal/types.ts
> +export type FinalizerLogic = Subscription | Unsubscribable | (() => void) | void;
The core team have to bike shed this one a bit. 

My gut tells me that `Finalizer` is enough. But I'd need to look at usage. It's really the observable's init return that this was created for.

That's one sort of problem with a big-bang PR like this.

2021-09-19 00:19 UTC, benlesh commented on src/internal/operators/catchError.ts
> +      // finalize right away. This ensures that `finalize` is called
```suggestion
      // finalize right away. This ensures that callbacks in the `finalize` operator are called
```

2021-09-19 00:22 UTC, benlesh requested changes
I absolutely love the initiative here. I think we may need to dial back the _code_ changes and keep the documentation/comment changes for now. There's going to be a lot of churn when we move to version 8, and changing some of the names of types and protected properties/methods might not be worth doing until a later time.

I'll mark this as an agenda item for the next core team meeting, but I think that for now we should probably undo any changes to developer-facing APIs.

2021-09-22 20:15 UTC, benlesh commented
Core team meeting: For APIs, go ahead and deprecate and update names. However, we're not going to remove anything newly deprecated until version 9 at this point. To give people a chance to adapt.

Also: `FinalizerLogic` should just be `Finalizer`.

2021-11-13 09:56 UTC, sangxxh commented
Hi @benlesh, any update for this PR?

2022-01-11 14:42 UTC, benlesh approved these changes

2022-01-11 14:46 UTC, benlesh commented
@sangxxh Sorry for the delay. This looks good. Can you please resolve the conflicts so I can get this merged? Thanks.

2022-02-22 15:46 UTC, merged