Raveclassic/fix subscriber next
ReactiveX/rxjs pull request #7172
Opened 2023-01-25 14:07 UTC by raveclassic

**Description:**

This PR fixes type signature of `Subscriber.next` method that was previously taking optional argument which was violating generic constraint `T`.

**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/2852

2023-01-25 17:12 UTC, benlesh approved these changes

2023-01-25 17:12 UTC, benlesh commented
Yay! I almost forgot we were waiting for v8 for this one.

2023-01-25 22:43 UTC, raveclassic commented
Awesome! Thanks for approving!
Seems I have to fix some things, missed that. Will come back to this PR when I return back to my laptop 🌴

2023-01-26 14:48 UTC, benlesh requested changes
Uh oh. We have broken tests.

2023-01-31 10:06 UTC, raveclassic commented
@benlesh tests are fixed 🤌

2023-02-18 15:58 UTC, raveclassic commented
@benlesh could you review, please?

2023-03-13 10:18 UTC, raveclassic commented
@benlesh just a friendly reminder ;) would love this to land in `rxjs@7` as now our codebase heavily relies on `new Observable(subscriber => {})` notation and we'd love to have this fixed 🙏

2023-05-23 16:10 UTC, LcsGa approved these changes

2023-06-15 09:38 UTC, raveclassic commented
Folks? :D @benlesh @LcsGa

2023-06-15 09:42 UTC, LcsGa commented
Hello! Sorry, I can't do more I'm not in the team 😅

2023-06-16 00:56 UTC, benlesh approved these changes

2023-06-16 00:56 UTC, merged

2023-06-16 12:04 UTC, jakovljevic-mladen commented
@benlesh, is this merged to `7.x` by mistake or on purpose?

2023-06-19 15:54 UTC, benlesh commented
That's a mistake, actually. :\ I did it on mobile and didn't notice. Damn.

2023-06-19 15:55 UTC, raveclassic commented
@jakovljevic-mladen @benlesh I expected this to land on 7.x 🤔

2023-06-19 15:56 UTC, benlesh commented
@jakovljevic-mladen honestly, I didn't notice, but I'm generally okay with this as a "fix" in 7.x. I'll go back and have a look to double check, but I think this is a valid bug fix, as people should not be calling `next()` on a `Subscriber<number>` or something. Type safety is important.