fix: SEO Page Title for Operator Decision Tree
ReactiveX/rxjs pull request #7326
Opened 2023-08-19 13:00 UTC by ajitzero

**Description:**
- Page title for "Operator Decision Tree" does not get picked from within the component.
- Page title for "Team" does not get picked from within the component.
- Typo: "Alumn" should be "Alumni".

**Related issue (if exists):**
None

2023-12-21 09:46 UTC, jakovljevic-mladen requested changes
Please revert one of the changes (the second example from the PR description) as it is redundant. And also please merge master branch to resolve conflicts. Otherwise, looks good.

2023-12-21 09:46 UTC, jakovljevic-mladen commented on docs_app/content/marketing/team.html
> +<h1 class="no-toc">Team</h1>
I think this heading is not needed. The reason for this is that the heading is still visible in the top header:

<img width="999" alt="image" src="https://github.com/ReactiveX/rxjs/assets/28087049/4b3f0b2d-daea-4e8a-a62e-8b0adc438246">

Please revert this one.

2023-12-21 09:46 UTC, jakovljevic-mladen commented on docs_app/content/marketing/contributors.json
> +    "group": "Alumni"
As a non-native English speaker, I hope this one is right 🙂  I don't really know. Maybe @benlesh can help?

2026-07-22 19:29 UTC, benlesh commented
Hi @ajitzero — thank you for the time, care, and thoughtfulness you put into this pull request. I’m sorry we weren’t able to respond in a reasonable timeframe. Since the codebase and surrounding context have moved on and this hasn’t seen recent activity, I’m going to close it for now. That’s a reflection of our delayed triage, not a lack of appreciation for your contribution. If the change is still relevant, please feel welcome to open a fresh pull request against the current codebase. Thank you again for contributing to RxJS and for your patience.

— Ben

<!-- rxjs-maintenance:close:pr:7326 -->

2026-07-22 19:29 UTC, closed without merging