Fixes a broken link to /api/operators/switchMapTo
ReactiveX/rxjs pull request #7370
Opened 2023-10-30 18:43 UTC by archubbuck

**Description:**

In the current version, the link does not resolve, but with this change, it navigates users properly.

2023-10-30 21:24 UTC, archubbuck commented
@jakovljevic-mladen, please let me know if any additional details are needed. Thanks!

2023-10-30 22:08 UTC, jakovljevic-mladen requested changes
Thanks for the fix. LGTM, however, a label should be updated as well.

2023-10-30 22:08 UTC, jakovljevic-mladen commented on apps/rxjs.dev/content/deprecations/resultSelector.md
> +- [swithMapTo](/api/operators/switchMapTo)
A label should be updated as well:

```suggestion
- [switchMapTo](/api/operators/switchMapTo)
```

2023-10-31 15:45 UTC, archubbuck commented on apps/rxjs.dev/content/deprecations/resultSelector.md
> +- [swithMapTo](/api/operators/switchMapTo)
Excellent catch, thanks!

2023-11-03 15:29 UTC, benlesh approved these changes

2023-11-03 15:30 UTC, merged

2023-11-03 15:30 UTC, benlesh commented
Thank you, @archubbuck