chore: set primary node version and yarn v1 package manager
ReactiveX/rxjs pull request #7380
Opened 2023-11-20 18:33 UTC by JamesHenry

**Description:**

In getting started with the repo, my global yarn installation of latest v4 tried to upgrade the repo.

This PR adds a volta config so that those that use it to manager their node toolchain can benefit from automatic resolution of node and yarn, and also adds a `packageManager` definition for corepack users.

This should make it easier for first time contributors to get up and running faster.

2023-11-20 18:34 UTC, JamesHenry commented on .github/workflows/ci_main.yml
> -        if: ${{ matrix.node == '18' || matrix.node == '20' }}
I imagine these conditions originally distinguished these steps, but as it stands now we only run the jobs on v18 and v20 so the condition is redundant and I went ahead and cleaned them up

2023-11-20 18:38 UTC, kwonoj requested changes
I believe setting engines field should be enough, if not we should set corepack related config only instead of having other 3rd party tools.

2023-11-20 18:46 UTC, JamesHenry commented
@kwonoj just to be clear, no third party tools are introduced here, purely config for volta users to benefit from if they already use the tool. It will be safely ignored by everything else and will not impact installs in any way. Do you still have an objection to it?

2023-11-20 19:15 UTC, kwonoj commented
> no third party tools are introduced here, purely config for volta users

I am well aware of volta and the what config those. I'm against our pkg manifest contains those tool specific configs. If there's a separate config file that's probably ok.

2023-11-20 19:19 UTC, JamesHenry commented
@kwonoj Ok I have replaced the volta config with an appropriate engines reference. Naturally this is only for the monorepo itself, rxjs users won't be impacted

2023-11-21 04:34 UTC, kwonoj approved these changes

2023-11-21 05:21 UTC, JamesHenry commented
Thanks for the approval @kwonoj are you able to approve the CI run?

2023-11-22 17:20 UTC, JamesHenry commented
@kwonoj following up on approving the CI run please

2023-11-22 19:48 UTC, merged