docs: use a processor to transform the operator decision tree data
ReactiveX/rxjs pull request #7388
Opened 2023-11-27 15:03 UTC by tmair

**Description:**
This PR moves the generation of the decision tree into a dgeni processor, so that the decision tree will be generated as part of the documentation generation.

**Related issue (if exists):**
None

2023-12-29 17:57 UTC, benlesh commented
Hey @tmair ! I really appreciate all of this good work. Generally, I'm not the one that reviews anything to do with the docs app, so I've been deferring to @jakovljevic-mladen and @niklas-wortmann for that. This seems like a nice add though.

2023-12-29 19:52 UTC, niklas-wortmann approved these changes
LGTM thanks for adjusting this

2024-01-03 14:09 UTC, jakovljevic-mladen requested changes
@tmair, this PR is awesome, thank you a lot for merging Operator Decision Tree generator to the tools that already exist.

I have one comment regarding a file rename; everything else looks great.

2024-01-03 14:53 UTC, tmair commented on apps/rxjs.dev/tools/transforms/config.js
> +const DECISION_TREE_PATH = resolve(CONTENTS_PATH, 'tree.yml');
Yes, that is a good remark. I renamed the file.

2024-01-03 14:54 UTC, tmair commented
> I have one comment regarding a file rename; everything else looks great. Also, conflicts need to be resolved.

I rebased the PR and addressed the comment about the renaming of the file.

2024-01-05 07:38 UTC, jakovljevic-mladen approved these changes
LGTM. Thanks a lot for making these changes @tmair 🎉

2024-01-05 07:39 UTC, merged